services:
  backend:
    build: ./backend
    container_name: backend-container
    env_file: ./backend/.env
    ports:
      - "8000:8000"
    networks:
      - app_network

  frontend:
    build: ./frontend
    container_name: frontend-container
    ports:
      - "5173:5173"
    networks:
      - app_network
    depends_on:
      - backend

networks:
  app_network:
    driver: bridge